add rpm build makefile
ao-space/space-agent pull request #25
Opened 2024-04-01 12:51 UTC by zxln007

for openEuler-24.03 , add rpm build makefile

2024-04-01 13:34 UTC, zxln007 reviewed
approve

2024-04-01 22:47 UTC, jianminww requested changes

2024-04-01 22:47 UTC, jianminww commented on Makefile
> +# ARCH ?= arm64
@zxln007 If the code will no longer be used, it would be better to remove it entirely rather than leaving it as a comment.

2024-04-02 00:58 UTC, jianminww approved these changes

2024-04-02 02:23 UTC, jack30724 approved these changes
approved.

2024-04-02 02:24 UTC, merged